dns:
  default-nameserver:
  - 2400:3200::1
  - 2400:3200:baba::1
  - 2606:4700:4700::1111
  - 2606:4700:4700::1001
  - '2402:4e00::'
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  - 223.5.5.5
  - 223.6.6.6
  - 119.29.29.29
  - 119.28.28.28
  direct-nameserver:
  - https://dns.google/dns-query
  - tls://dns.google
  - https://cloudflare-dns.com/dns-query
  - tls://one.one.one.one
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - 2606:4700:4700::1111
  - 2606:4700:4700::1001
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  - 114.114.114.114
  - 114.114.115.115
  - 223.5.5.5
  - 223.6.6.6
  - 119.29.29.29
  - 119.28.28.28
  direct-nameserver-follow-policy: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.arpa'
  - time.*.com
  - ntp.*.com
  - time.*.com
  - +.market.xiaomi.com
  - localhost.ptlogin2.qq.com
  - '*.msftncsi.com'
  - www.msftconnecttest.com
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fallback:
  - https://dns.google/dns-query
  - tls://dns.google
  - https://cloudflare-dns.com/dns-query
  - tls://one.one.one.one
  - 2606:4700:4700::1111
  - 2606:4700:4700::1001
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  fallback-filter:
    domain:
    - +.google.com
    - +.facebook.com
    - +.youtube.com
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  ipv6: true
  listen: 0.0.0.0:1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - 2400:3200::1
  - 2400:3200:baba::1
  - '2402:4e00::'
  - 223.5.5.5
  - 223.6.6.6
  - 119.29.29.29
  - 119.28.28.28
  prefer-h3: false
  proxy-server-nameserver:
  - https://dns.google/dns-query
  - tls://dns.google
  - https://cloudflare-dns.com/dns-query
  - tls://one.one.one.one
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - 2606:4700:4700::1111
  - 2606:4700:4700::1001
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - 2400:3200::1
  - 2400:3200:baba::1
  - '2402:4e00::'
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  - 223.5.5.5
  - 223.6.6.6
  - 119.29.29.29
  - 119.28.28.28
  respect-rules: false
  use-hosts: false
  use-system-hosts: false
